ShaveddaPizzariaWeb/Areas/Customer/Controllers/PizzaOrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShaveddaPizzaria.DataAccess.Data;
using ShaveddaPizzaria.DataAccess.Repository;
using ShaveddaPizzaria.DataAccess.Repository.IRepository;
using ShaveddaPizzaria.Models;

namespace ShaveddaPizzariaWeb.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class PizzaOrderController : Controller
    {
        private readonly IPizzaPresetRepository _presetRepo;
        private readonly IPizzaOrderRepository _orderRepo;
        private readonly IPizzaOrderDetailRepository _orderDetailRepo;

        public PizzaOrderController(IPizzaPresetRepository presetRepo, IPizzaOrderRepository orderRepo, IPizzaOrderDetailRepository orderDetailRepo)
        {
            _presetRepo = presetRepo;
            _orderRepo = orderRepo;
            _orderDetailRepo = orderDetailRepo;
        }

        public IActionResult Index()
        {
            return View(_orderRepo.GetAll());
        }

        public IActionResult OrderPreset(int? id)
        {
            PizzaPreset preset = _presetRepo.Get(u => u.PizzaId == id);
            if (preset == null)
            {
                return NotFound();
            }
            PizzaOrder pizzaOrder = new PizzaOrder();
            pizzaOrder.OrderDetails = new PizzaOrderDetails();
            pizzaOrder.OrderDetails.PizzaSauce = preset.PizzaSauce;
            pizzaOrder.OrderDetails.PizzaName = preset.PizzaName;
            pizzaOrder.OrderDetails.HasCheese = preset.HasCheese;
            pizzaOrder.OrderDetails.HasPepperoni = preset.HasPepperoni;
            pizzaOrder.OrderDetails.HasMushroom = preset.HasMushroom;
            pizzaOrder.OrderDetails.HasPineapple = preset.HasPineapple;
            pizzaOrder.OrderDetails.HasTuna = preset.HasTuna;
            pizzaOrder.OrderDetails.HasPrawn = preset.HasPrawn;
            pizzaOrder.OrderDetails.HasHam = preset.HasHam;
            pizzaOrder.OrderDetails.HasBeef = preset.HasBeef;

            ViewData["PresetImage"] = preset.ImagePath;
            return View(pizzaOrder);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult OrderPreset(PizzaOrder order)
        {
            order.Email = "mockemail@gmail.com";
            order.OrderDetails.TotalPrice = order.OrderDetails.CalculateTotalPrice();
            if (ModelState.IsValid)
            {
                _orderRepo.Add(order);
                _orderRepo.Save();
                TempData["success"] = "Order created successfully. Thank you for placing you order at Shavedda Pizzaria!";
                return RedirectToAction("Index");
            }
            return View(order);
        }

        public IActionResult CustomPizza()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CustomPizza(PizzaOrder order)
        {
            order.Email = "mockemail@gmail.com";
            order.OrderDetails.TotalPrice = order.OrderDetails.CalculateTotalPrice();
            if (ModelState.IsValid)
            {
                _orderRepo.Add(order);
                _orderRepo.Save();
                TempData["success"] = "Order created successfully. Thank you for placing you order at Shavedda Pizzaria!";
                return RedirectToAction("Index");
            }
            return View(order);
        }

        public IActionResult OrderDetail(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            try
            {
                var order = _orderRepo.Get(u => u.OrderId == id);
                return View(order);
            }
            catch (ArgumentNullException ex)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteOrder(int? id)
        {
            var order = _orderRepo.Get(u => u.OrderId == id);

            if (order == null)
            {
                return NotFound();
            }

            _orderRepo.Remove(order);
            _orderRepo.Save();
            TempData["success"] = "Order deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

ShaveddaPizzariaWeb/Areas/Customer/Views/PizzaOrder/CustomPizza.cshtml
@model ShaveddaPizzaria.Models.PizzaOrder

<div class="container font-monospace">
	<div>
		<h1 class="display-4 mt-4">Custom Pizza</h1>
		<hr />
	</div>
	<div class="border border-warning border-4 rounded-3 px-4 py-3 mt-4 bg-black bg-opacity-50">
		<div class="row mb-3">
			<div class="col-2">
				<a class="btn btn-danger col-md-8" asp-controller="Home" asp-action="Index">Back</a>
			</div>
			<div class="row col-8 justify-content-center">
				<div class="col-6">
					<img src="~/images/presets/Create.png" class="w-100" />
				</div>
			</div>
			<div class="col-2"></div>
		</div>
		<form method="post" class="was-validated" novalidate>
			<div class="row mb-3">
				<label class="col-sm-2 col-form-label col-form-label-lg text-white">Pizza name</label>
				<div class="col-sm-10">
					<input type="text" class="form-control form-control-lg" asp-for="OrderDetails.PizzaName" maxlength="30" required>
					<div class="invalid-feedback">
						Please enter a name.
					</div>
				</div>
			</div>
			<div class="row mb-3">
				<label class="col-sm-2 col-form-label col-form-label-lg text-white">Address</label>
				<div class="col-sm-10">
					<textarea type="text" class="form-control form-control-lg" rows="3" asp-for=Address maxlength="150" required></textarea>
					<div class="invalid-feedback">
						Please enter an address.
					</div>
				</div>
			</div>
			<div class="row mb-3">
				<label class="col-sm-2 col-form-label col-form-label-lg text-white">Size</label>
				<div class="col-sm-10">
					<select class="form-select form-select-lg" asp-for="OrderDetails.PizzaSize" asp-items="Html.GetEnumSelectList<PizzaSize>()" required>
						<option value="" selected disabled>--Select Size--</option>
					</select>
					<div class="invalid-feedback">
						Please select a size.
					</div>
				</div>
			</div>
			<div class="row mb-3">
				<label class="col-sm-2 col-form-label col-form-label-lg text-white">Sauce</label>
				<div class="col-sm-10">
					<select class="form-select form-select-lg" asp-for="OrderDetails.PizzaSauce" asp-items="Html.GetEnumSelectList<PizzaSauce>()" required>
						<option value="" selected disabled>--Select Sauce--</option>
					</select>
					<div class="invalid-feedback">
						Please select a sauce.
					</div>
				</div>
			</div>
			<fieldset class="row mt-2 mb-3">
				<legend class="col-sm-2 col-form-label col-form-label-lg pt-0">Ingredients</legend>
				<div class="col-sm-5 form-check">
					<div class="form-check ps-0">
						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasCheese" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="OrderDetails.HasCheese">Cheese</label>

						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasPepperoni" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="OrderDetails.HasPepperoni">Pepperoni</label>

						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasMushroom" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="OrderDetails.HasMushroom">Mushroom</label>

						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasPineapple" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="OrderDetails.HasPineapple">Pineapple</label>

						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasTuna" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="OrderDetails.HasTuna">Tuna</label>

						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasPrawn" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="OrderDetails.HasPrawn">Prawn</label>

						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasHam" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="OrderDetails.HasHam">Ham</label>

						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasBeef" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="OrderDetails.HasBeef">Beef</label>
					</div>
				</div>
			</fieldset>
			<div class="d-grid">
				<button type="submit" class="btn btn-lg btn-warning">
					<i class="bi bi-cart-check"></i>&nbsp;Order!
				</button>
			</div>

		</form>
	</div>
</div>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

ShaveddaPizzariaWeb/Areas/Customer/Views/PizzaOrder/Index.cshtml
@model IEnumerable<PizzaOrder>

<div class="container font-monospace">
	<div class="mt-4">
		<h2 class="display-4" style="letter-spacing: 1px;">Pizza Orders</h2>
		<hr />
	</div>
	<div class="table-responsive text-break">
		<table class="table table-striped table-hover">
			<thead>
				<tr class="fs-5">
					<th class="ps-3">
						Email
					</th>
					<th>
						Pizza Name
					</th>
					<th>
						Address
					</th>
					<th>

					</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var order in Model)
				{
					<tr class="align-middle">
						<td class="ps-4">
							@order.Email
						</td>
						<td class="col-3">
							@order.OrderDetails.PizzaName
						</td>
						<td class="col-4 align-middle">
							@order.Address
						</td>
						<td class="col-3 text-end">
							<a class="btn btn-outline-info col-md-5" asp-controller="PizzaOrder" asp-action="OrderDetail" asp-route-id="@order.OrderId">
								<i class="bi bi-justify"></i>&nbsp;Details
							</a>
							<a class="btn btn-outline-danger col-md-5" data-bs-toggle="modal" data-bs-target="#deleteConfirmation-@order.OrderDetails.PizzaId">
								<i class="bi bi-trash3"></i>&nbsp;Delete
							</a>
							@{
								Html.RenderPartial("_DeleteConfirmation", new DeleteData(@order.OrderDetails.PizzaId, @order.GetType()));
							}
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>

ShaveddaPizzariaWeb/Areas/Customer/Views/PizzaOrder/OrderDetail.cshtml
@model ShaveddaPizzaria.Models.PizzaOrder

<div class="container font-monospace">
	<div>
		<h1 class="display-4 mt-4">Order Detail</h1>
		<hr />
	</div>
	<form>
		<div class="row justify-content-center">
			<div class="col-8 border border-warning border-4 rounded-3 px-4 py-3 mt-4 bg-black bg-opacity-50">
				<div class="row mb-3 mt-0">
					<label class="col-sm-3 col-form-label col-form-label-lg text-white" asp-for="Email">Email</label>
					<div class="col-sm-9">
						<input type="text" asp-for="Email" class="form-control-plaintext form-control-lg" readonly>
					</div>
				</div>
				<div class="row mb-3 mt-0">
					<label class="col-sm-3 col-form-label col-form-label-lg text-white" asp-for="Address">Address</label>
					<div class="col-sm-9">
						<textarea type="text" rows="3" asp-for="Address" 
							class="form-control-plaintext form-control-lg text-break"
							style="resize: none;" readonly>
					</textarea>
					</div>
				</div>
				<div class="row mb-3 mt-0">
					<label class="col-sm-3 col-form-label col-form-label-lg text-white" asp-for="OrderDetails.PizzaName">Pizza name</label>
					<div class="col-sm-9">
						<input type="text" asp-for="OrderDetails.PizzaName" class="form-control-plaintext form-control-lg" readonly>
					</div>
				</div>
				<div class="row mb-3">
					<label class="col-sm-3 col-form-label col-form-label-lg text-white">Size</label>
					<div class="col-sm-9">
						<input type="text" asp-for="OrderDetails.PizzaSize" class="form-control-plaintext form-control-lg" readonly>
					</div>
				</div>
				<div class="row mb-3">
					<label class="col-sm-3 col-form-label col-form-label-lg text-white">Sauce</label>
					<div class="col-sm-9">
						<input type="text" asp-for="OrderDetails.PizzaSauce" class="form-control-plaintext form-control-lg" readonly>
					</div>
				</div>
				<fieldset class="row mb-3">
					<legend class="col-sm-3 col-form-label col-form-label-lg pt-0">Ingredients</legend>
					<div class="col-sm-9 form-check" style="font-size: larger">
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="OrderDetails.HasCheese">
							<label style="pointer-events: none;" asp-for="OrderDetails.HasCheese">Cheese</label>
						</div>
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="OrderDetails.HasPepperoni">
							<label style="pointer-events: none;" asp-for="OrderDetails.HasPepperoni">Pepperoni</label>
						</div>
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="OrderDetails.HasMushroom">
							<label style="pointer-events: none;" asp-for="OrderDetails.HasMushroom">Mushroom</label>
						</div>
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="OrderDetails.HasPineapple">
							<label style="pointer-events: none;" asp-for="OrderDetails.HasPineapple">Pineapple</label>
						</div>
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="OrderDetails.HasTuna">
							<label style="pointer-events: none;" asp-for="OrderDetails.HasTuna">Tuna</label>
						</div>
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="OrderDetails.HasPrawn">
							<label style="pointer-events: none;" asp-for="OrderDetails.HasPrawn">Prawn</label>
						</div>
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="OrderDetails.HasHam">
							<label style="pointer-events: none;" asp-for="OrderDetails.HasHam">Ham</label>
						</div>
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="OrderDetails.HasBeef">
							<label style="pointer-events: none;" asp-for="OrderDetails.HasBeef">Beef</label>
						</div>
					</div>	
				</fieldset>
				<div class="row mb-3 mt-0 justify-content-end">
					<label class="col-auto col-form-label col-form-label-lg text-white" asp-for="OrderDetails.TotalPrice">Total price:</label>
					<div class="col-1">
						<input type="text" asp-for="OrderDetails.TotalPrice" class="form-control-plaintext form-control-lg" readonly>
					</div>
				</div>
				<a class="btn btn-danger" style="width:150px;" asp-controller="PizzaOrder" asp-action="Index">Back to List</a>
			</div>
		</div>
	</form>
</div>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

ShaveddaPizzariaWeb/Areas/Customer/Views/PizzaOrder/OrderPreset.cshtml
@model ShaveddaPizzaria.Models.PizzaOrder
@{
	string presetImage = ViewData["PresetImage"] as string;
	Console.WriteLine(presetImage);
}

<div class="container font-monospace">
	<div>
		<h1 class="display-4 mt-4">Customize</h1>
		<hr />
	</div>
	<div class="border border-warning border-4 rounded-3 px-4 py-3 mt-4 bg-black bg-opacity-50">
		<div class="row justify-content-center">
			<div class="col-4 mb-2 align-middle align-self-center">
				<img src=@presetImage class="w-100 bg-black bg-opacity-50 border border-3 border-primary rounded-2" asp-append-version=true />
			</div>
		</div>
		<form method="post" class="was-validated" asp-action="orderPreset" novalidate>
			<div class="row mb-3">
				<label class="col-sm-2 col-form-label col-form-label-lg text-white">Pizza name</label>
				<div class="col-sm-10">
					<input type="text" class="form-control-plaintext form-control-lg" asp-for="OrderDetails.PizzaName" readonly>
				</div>
			</div>
			<div class="row mb-3">
				<label class="col-sm-2 col-form-label col-form-label-lg text-white">Address</label>
				<div class="col-sm-10">
					<textarea type="text" class="form-control form-control-lg" rows="3" asp-for=Address maxlength="150" required></textarea>
					<div class="invalid-feedback">
						Please enter an address.
					</div>
				</div>
			</div>
			<div class="row mb-3">
				<label class="col-sm-2 col-form-label col-form-label-lg text-white">Size</label>
				<div class="col-sm-10">
					<select class="form-select form-select-lg" asp-for="OrderDetails.PizzaSize" asp-items="Html.GetEnumSelectList<PizzaSize>()" required>
						<option value="" selected disabled>--Select Size--</option>
					</select>
					<div class="invalid-feedback">
						Please select a size.
					</div>
				</div>
			</div>
			<div class="row mb-3">
				<label class="col-sm-2 col-form-label col-form-label-lg text-white">Sauce</label>
				<div class="col-sm-10">
					<select class="form-select form-select-lg" asp-for="OrderDetails.PizzaSauce" asp-items="Html.GetEnumSelectList<PizzaSauce>()" required>
						<option value="" selected disabled>--Select Sauce--</option>
					</select>
					<div class="invalid-feedback">
						Please select a sauce.
					</div>
				</div>
			</div>
			<fieldset class="row mt-2 mb-3">
				<legend class="col-sm-2 col-form-label col-form-label-lg pt-0">Ingredients</legend>
				<div class="col-sm-5 form-check">
					<div class="form-check ps-0">
						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasCheese" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="OrderDetails.HasCheese">Cheese</label>

						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasPepperoni" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2"  asp-for="OrderDetails.HasPepperoni">Pepperoni</label>

						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasMushroom" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="OrderDetails.HasMushroom">Mushroom</label>

						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasPineapple" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="OrderDetails.HasPineapple">Pineapple</label>

						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasTuna" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="OrderDetails.HasTuna">Tuna</label>

						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasPrawn" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="OrderDetails.HasPrawn">Prawn</label>

						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasHam" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="OrderDetails.HasHam">Ham</label>

						<input type="checkbox" class="btn-check" asp-for="OrderDetails.HasBeef" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="OrderDetails.HasBeef">Beef</label>
					</div>
				</div>
			</fieldset>
			<div class="d-grid">
				<button type="submit" class="btn btn-lg btn-warning">
					<i class="bi bi-cart-check"></i>&nbsp;Order!
				</button>
			</div>

		</form>
	</div>
</div>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}