ShaveddaPizzariaWeb/Areas/Admin/Controllers/PizzaPresetController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShaveddaPizzaria.DataAccess.Data;
using ShaveddaPizzaria.DataAccess.Repository;
using ShaveddaPizzaria.DataAccess.Repository.IRepository;
using ShaveddaPizzaria.Models;

namespace ShaveddaPizzariaWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PizzaPresetController : Controller
    {
        private readonly IPizzaPresetRepository _presetRepo;
        private readonly IWebHostEnvironment _webHostEnvironment;

        private const string DEFAULT_PRESET_IMAGE = @"\images\presets\Create.png";

        public PizzaPresetController(IPizzaPresetRepository presetRepo, IWebHostEnvironment webHostEnvironment)
        {
            _presetRepo = presetRepo;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View(_presetRepo.GetAll());
        }

        public IActionResult UpsertPreset(int? id)
        {
            if (id == null || id == 0)
            {
                return View(new PizzaPreset());
            }
            else
            {
                PizzaPreset preset = _presetRepo.Get(u => u.PizzaId == id);
                return View(preset);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpsertPreset(PizzaPreset preset, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string presetPath = Path.Combine(wwwRootPath, @"images\presets");

                    DeleteOldImage(preset, wwwRootPath);

                    using (var fileStream = new FileStream(Path.Combine(presetPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    preset.ImagePath = @"\images\presets\" + fileName;
                }

                if (preset.PizzaId == 0)
                {
                    if (string.IsNullOrEmpty(preset.ImagePath))
                    {
                        preset.ImagePath = @"\images\presets\Create.png";
                    }
                    _presetRepo.Add(preset);
                    TempData.Add("success", "Preset created successfully");
                }
                else
                {
                    _presetRepo.Update(preset);
                    TempData.Add("success", "Preset edited successfully");
                }

                _presetRepo.Save();
                return RedirectToAction("Index");
            }
            return View(preset);
        }

        public IActionResult PresetDetail(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var preset = _presetRepo.Get(u => u.PizzaId == id);

            if (preset == null)
            {
                return NotFound();
            }

            return View(preset);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePreset(int? id)
        {
            var preset = _presetRepo.Get(u => u.PizzaId == id);

            if (preset == null)
            {
                return NotFound();
            }

            DeleteOldImage(preset, _webHostEnvironment.WebRootPath);
            _presetRepo.Remove(preset);
            _presetRepo.Save();
            TempData["success"] = "Preset deleted successfully";
            return RedirectToAction("Index");
        }

        private void DeleteOldImage(PizzaPreset preset, string wwwRootPath)
        {
            if (!string.IsNullOrEmpty(preset.ImagePath))
            {
                // Delete old image
                var oldImagePath = Path.Combine(wwwRootPath, preset.ImagePath.TrimStart('\\'));
                var defaultImagePath = Path.Combine(wwwRootPath, DEFAULT_PRESET_IMAGE.TrimStart('\\'));

                if (System.IO.File.Exists(oldImagePath) && !oldImagePath.Equals(defaultImagePath))
                {
                    System.IO.File.Delete(oldImagePath);
                }

            }
        }
    }
}

ShaveddaPizzariaWeb/Controllers/PizzaPresetController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShaveddaPizzaria.DataAccess.Data;
using ShaveddaPizzaria.DataAccess.Repository;
using ShaveddaPizzaria.DataAccess.Repository.IRepository;
using ShaveddaPizzaria.Models;

namespace ShaveddaPizzariaWeb.Controllers
{
    public class PizzaPresetController : Controller
    {
        private readonly IPizzaPresetRepository _presetRepo;
        private readonly IWebHostEnvironment _webHostEnvironment;

        private const string DEFAULT_PRESET_IMAGE = @"\images\presets\Create.png";

		public PizzaPresetController(IPizzaPresetRepository presetRepo, IWebHostEnvironment webHostEnvironment)
		{
			_presetRepo = presetRepo;
			_webHostEnvironment = webHostEnvironment;
		}

		public IActionResult Index()
        {
            return View(_presetRepo.GetAll());
        }

        public IActionResult UpsertPreset(int? id)
        {
            if(id == null || id == 0)
            {
                return View(new PizzaPreset());
            }
            else
            {
                PizzaPreset preset = _presetRepo.Get(u => u.PizzaId == id);
                return View(preset);
            }
        }

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult UpsertPreset(PizzaPreset preset, IFormFile? file)
		{
			if (ModelState.IsValid)
			{
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if(file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string presetPath = Path.Combine(wwwRootPath, @"images\presets");

                    DeleteOldImage(preset, wwwRootPath);

                    using (var fileStream = new FileStream(Path.Combine(presetPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    preset.ImagePath = @"\images\presets\" + fileName;
                }

                if(preset.PizzaId == 0)
                {
                    if(string.IsNullOrEmpty(preset.ImagePath))
                    {
                        preset.ImagePath = @"\images\presets\Create.png";
                    }
					_presetRepo.Add(preset);
					TempData.Add("success", "Preset created successfully");
				}
                else
                {
					_presetRepo.Update(preset);
					TempData.Add("success", "Preset edited successfully");
				}

				_presetRepo.Save();
				return RedirectToAction("Index");
			}
			return View(preset);
		}

        public IActionResult PresetDetail(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var preset = _presetRepo.Get(u => u.PizzaId == id);

			if (preset == null)
            {
                return NotFound();
            }

            return View(preset);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePreset(int? id)
        {
            var preset = _presetRepo.Get(u => u.PizzaId == id);

			if (preset == null)
            {
                return NotFound();
            }

			DeleteOldImage(preset, _webHostEnvironment.WebRootPath);
			_presetRepo.Remove(preset);
			_presetRepo.Save();
			TempData["success"] = "Preset deleted successfully";
            return RedirectToAction("Index");
        }

        private void DeleteOldImage(PizzaPreset preset, string wwwRootPath)
        {
			if (!string.IsNullOrEmpty(preset.ImagePath))
			{
				// Delete old image
				var oldImagePath = Path.Combine(wwwRootPath, preset.ImagePath.TrimStart('\\'));
				var defaultImagePath = Path.Combine(wwwRootPath, DEFAULT_PRESET_IMAGE.TrimStart('\\'));

				if (System.IO.File.Exists(oldImagePath) && !oldImagePath.Equals(defaultImagePath))
				{
					System.IO.File.Delete(oldImagePath);
				}

			}
		}
	}
}

ShaveddaPizzariaWeb/Areas/Admin/Views/PizzaPreset/Index.cshtml
@model IEnumerable<PizzaPreset>

<div class="container font-monospace">
	<div class="mt-4">
		<h2 class="display-4" style="letter-spacing: 1px;">Pizza Presets</h2>
		<hr />
	</div>
	<div class="text-end mb-2">
		<a class="btn btn-outline-warning" asp-controller="PizzaPreset" asp-action="UpsertPreset">
			<i class="bi bi-plus-circle"></i>&nbsp;Create New
		</a>
	</div>
	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th class="ps-3 fs-5">
					Name
				</th>
				<th>

				</th>
			</tr>
		</thead>
		<tbody>
			@foreach(var preset in Model)
			{
				<tr class="align-middle">
					<td class="col-7 ps-4">
						@preset.PizzaName
					</td>
					<td class="col-5 text-end">
						<a class="btn btn-outline-primary col-md-3" asp-controller="PizzaPreset" asp-action="UpsertPreset" asp-route-id="@preset.PizzaId">
							<i class="bi bi-pencil-square"></i>&nbsp;Edit
						</a>
						<a class="btn btn-outline-info col-md-3" asp-controller="PizzaPreset" asp-action="PresetDetail" asp-route-id="@preset.PizzaId">
							<i class="bi bi-justify"></i>&nbsp;Details
						</a>
						<a class="btn btn-outline-danger col-md-3" data-bs-toggle="modal" data-bs-target="#deleteConfirmation-@preset.PizzaId">
							<i class="bi bi-trash3"></i>&nbsp;Delete
						</a>
						@{
							Html.RenderPartial("_DeleteConfirmation", new DeleteData(@preset.PizzaId, @preset.GetType()));
						}
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>

ShaveddaPizzariaWeb/Areas/Admin/Views/PizzaPreset/PresetDetail.cshtml
@model ShaveddaPizzaria.Models.PizzaPreset

<div class="container font-monospace">
	<div>
		<h1 class="display-4 mt-4">Preset Detail</h1>
		<hr />
	</div>
	<form>
		<div class="row justify-content-center">
			<div class="col-8 border border-warning border-4 rounded-3 px-4 py-3 mt-4 bg-black bg-opacity-50">

				<div class="row mt-2 mb-2 justify-content-center">
					<div class="col-5">
						@{
							<img src="@Model.ImagePath" class="w-100 bg-black bg-opacity-50 border border-3 border-primary rounded-2" asp-append-version="true" />
						}
					</div>
				</div>

				<div class="row mb-3 mt-0">
					<label class="col-sm-3 col-form-label col-form-label-lg text-white" asp-for="PizzaName">Pizza name</label>
					<div class="col-sm-9">
						<input type="text" asp-for="PizzaName" class="form-control-plaintext form-control-lg" readonly>
					</div>
				</div>
				<div class="row mb-3">
					<label class="col-sm-3 col-form-label col-form-label-lg text-white">Sauce</label>
					<div class="col-sm-9">
						<input type="text" asp-for="PizzaSauce" class="form-control-plaintext form-control-lg" readonly>
					</div>
				</div>
				<fieldset class="row mb-3">
					<legend class="col-sm-3 col-form-label col-form-label-lg pt-0">Ingredients</legend>
					<div class="col-sm-9 form-check" style="font-size: larger">
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="HasCheese">
							<label style="pointer-events: none;" asp-for="HasCheese">Cheese</label>
						</div>
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="HasPepperoni">
							<label style="pointer-events: none;" asp-for="HasPepperoni">Pepperoni</label>
						</div>
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="HasMushroom">
							<label style="pointer-events: none;" asp-for="HasMushroom">Mushroom</label>
						</div>
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="HasPineapple">
							<label style="pointer-events: none;" asp-for="HasPineapple">Pineapple</label>
						</div>
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="HasTuna">
							<label style="pointer-events: none;" asp-for="HasTuna">Tuna</label>
						</div>
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="HasPrawn">
							<label style="pointer-events: none;" asp-for="HasPrawn">Prawn</label>
						</div>
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="HasHam">
							<label style="pointer-events: none;" asp-for="HasHam">Ham</label>
						</div>
						<div class="form-check ps-0">
							<input type="checkbox" style="pointer-events: none; transform: scale(1.3)" asp-for="HasBeef">
							<label style="pointer-events: none;" asp-for="HasBeef">Beef</label>
						</div>
					</div>
				</fieldset>
				<a class="btn btn-danger" style="width:150px;" asp-controller="PizzaPreset" asp-action="Index">Back to List</a>
			</div>
		</div>
	</form>
</div>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

ShaveddaPizzariaWeb/Areas/Admin/Views/PizzaPreset/UpsertPreset.cshtml
@model ShaveddaPizzaria.Models.PizzaPreset
@{
	string presetImage = Model.ImagePath;
	if(!string.IsNullOrEmpty(presetImage))
	{
		presetImage = presetImage.Replace(@"\", @"\\");
	}
}

<div class="container font-monospace">
	<div>
		<h1 class="display-4 mt-4"> @( Model.PizzaId == 0 ? "Create Preset" : "Edit Preset" ) </h1>
		<hr />
	</div>
	<form method="post" class="was-validated" enctype="multipart/form-data" novalidate>
		<div class="border border-warning border-4 rounded-3 px-4 py-3 mt-4 bg-black bg-opacity-50">

			<input asp-for="PizzaId" hidden>
			<input asp-for="ImagePath" hidden>
			
			<div class="row mb-3">
				<label asp-for="PizzaName" class="col-sm-2 col-form-label col-form-label-lg text-white">Pizza name</label>
				<div class="col-sm-10">
					<input type="text" asp-for="PizzaName" class="form-control form-control-lg" maxlength="30" required>	
					<div class="invalid-feedback">
						Please enter a name.
					</div>
				</div>
			</div>
			<div class="row mb-3">
				<label asp-for="ImagePath" class="col-sm-2 col-form-label col-form-label-lg text-white">Preset image</label>
				<div class="col-sm-10">
					<input type="file" name="file" id="upload" class="form-control form-control-lg" onchange="displaySelectedImage(event, 'selectedImage', '@presetImage')" />
				</div>
			</div>
			<div class="row mb-3 justify-content-center">
				<div class="col-sm-3">
					@{
						if (Model.ImagePath == null)
						{
							<img id="selectedImage" src="\images\placeholder.jpg" class="w-100 bg-black bg-opacity-50 img-thumbnail" />
						}
						else
						{
							<img id="selectedImage" src="@Model.ImagePath" class="w-100 bg-black bg-opacity-50 img-thumbnail" />
						}
					}
					
				</div>
			</div>
			<div class="row mb-3">
				<label class="col-sm-2 col-form-label col-form-label-lg text-white">Sauce</label>
				<div class="col-sm-10">
					<select class="form-select form-select-lg" asp-for="PizzaSauce" asp-items="Html.GetEnumSelectList<PizzaSauce>()" required>
						<option value="" selected disabled>--Select Sauce--</option>
					</select>
					<div class="invalid-feedback">
						Please select a sauce.
					</div>
				</div>
			</div>
			<fieldset class="row mb-3">
				<legend class="col-sm-2 col-form-label col-form-label-lg pt-0">Ingredients</legend>
				<div class="col-sm-5 form-check">
					<div class="form-check ps-0">
						<input type="checkbox" class="btn-check" asp-for="HasCheese" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="HasCheese">Cheese</label>

						<input type="checkbox" class="btn-check" asp-for="HasPepperoni" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="HasPepperoni">Pepperoni</label>

						<input type="checkbox" class="btn-check" asp-for="HasMushroom" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="HasMushroom">Mushroom</label>

						<input type="checkbox" class="btn-check" asp-for="HasPineapple" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="HasPineapple">Pineapple</label>

						<input type="checkbox" class="btn-check" asp-for="HasTuna" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="HasTuna">Tuna</label>

						<input type="checkbox" class="btn-check" asp-for="HasPrawn" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="HasPrawn">Prawn</label>

						<input type="checkbox" class="btn-check" asp-for="HasHam" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="HasHam">Ham</label>

						<input type="checkbox" class="btn-check" asp-for="HasBeef" autocomplete="off">
						<label class="btn btn-outline-primary mb-3 me-2" asp-for="HasBeef">Beef</label>
					</div>
				</div>
			</fieldset>
			@if(Model.PizzaId == 0)
			{
				<button type="submit" class="btn btn-warning" style="width:150px;">Create</button>
			}
			else
			{
				<button type="submit" class="btn btn-warning" style="width:150px;">Update</button>
			}
			
			<a class="btn btn-danger" style="width:150px;" asp-controller="PizzaPreset" asp-action="Index">Back to List</a>
		</div>
	</form>
</div>

@section Scripts {
	<script>
		function displaySelectedImage(event, elementId, presetImage) {
			const selectedImage = document.getElementById(elementId);
			const fileInput = event.target;

			if (fileInput.files && fileInput.files[0]) {
				const reader = new FileReader();

				reader.onload = function (e) {
					selectedImage.src = e.target.result;
				};

				reader.readAsDataURL(fileInput.files[0]);
			}
			else 
			{
				if (!presetImage) {
					selectedImage.src = "\\images\\placeholder.jpg";
				}
				else 
				{ 
					selectedImage.src = presetImage;
				}
			}
		}
	</script>

	@{
			<partial name="_ValidationScriptsPartial" />
	}
}